version: '3.9'
services:
    database:
        image: postgres:16.4
        ports:
            - "54321:5432"
        environment:
            - POSTGRES_DB=portal_template
            - POSTGRES_USER=portal-template
            - POSTGRES_PASSWORD=portal-template
