server:
    port: 8080

spring:
    application:
        name: portal-backend-template
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8082/auth/realms/master
    liquibase:
        enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: #env var
        name: portal-template
        username: #env var
        password: #env var
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

graphql:
    packages:
        - "com.ritense.portal"
logging:
    level:
        org:
            springframework:
                amqp: DEBUG