server:
    port: 8090

spring:
    application:
        name: portal-backend-template
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: #externaly overwritten
    liquibase:
        enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: #externaly overwritten
        username: #externaly overwritten
        password: #externaly overwritten

graphql:
    packages:
        - "com.ritense.portal"

logging:
    level:
        org:
            springframework:
                amqp: DEBUG

valtimo:
    openzaak:
        url: http://localhost:8001
        clientId: gzac
        secret: # set with environment variable
    cors:
        -   path: "/**"
            config:
                allowedHeaders: "*"
                allowedOrigins: "*"
                allowedMethods: "*"
