# Values here are setup to work with the nl-portal-docker-compose repository

server:
    port: 8080

management:
    endpoint:
        health:
            enabled: true
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: health
        enabled-by-default: false

spring:
    application:
        name: portal-backend-template
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:8082/auth/realms/nlportal
    liquibase:
        enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: #env var
        name: portal-template
        username: #env var
        password: #env var
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect

keycloak:
    resource: gzac-portal-m2m
    audience: gzac-portal-token-exchange
    credentials:
        secret: ookVRUAxmEWMcosfcGR5nxeoUC4Rgwbc
graphql:
    packages:
        - "nl.nlportal"
logging:
    level:
        root: DEBUG
        org:
            springframework:
                amqp: DEBUG
nl-portal:
    zgw:
        besluiten:
            url: http://localhost:8001
            clientId: valtimo_client
            secret: e09b8bc5-5831-4618-ab28-41411304309d
        catalogiapi:
            url: http://localhost:8001
            clientId: valtimo_client
            secret: e09b8bc5-5831-4618-ab28-41411304309d
            rsin: "051845623"
            documentTypeUrl: http://host.docker.internal:8001/catalogi/api/v1/informatieobjecttypen/efc332f2-be3b-4bad-9e3c-49a6219c92ad
        zakenapi:
            url: http://localhost:8001
            clientId: valtimo_client
            secret: e09b8bc5-5831-4618-ab28-41411304309d
            zaak-documenten:
                vertrouwelijkheidsaanduiding-whitelist:
                    - openbaar
                    - beperkt_openbaar
                    - intern
                    - zaakvertrouwelijk
                    - vertrouwelijk
                    - confidentieel
                    - geheim
                    - zeer_geheim
                status-whitelist:
                    - ter_vaststelling
                    - in_bewerking
                    - definitief
                    - gearchiveerd
        taak:
            taakobject:
                typeUrl: "http://host.docker.internal:8011/api/v1/objecttypes/3e852115-277a-4570-873a-9a64be3aeb34"
                type-url-v2: "http://host.docker.internal:8011/api/v1/objecttypes/3e852115-277a-4570-873a-9a64be3aeb34"
        documentenapis:
            #virusscan:
            #clamav:
            #hostName: localhost
            #enabled: true
            default-document-api: openzaak
            configurations:
                openzaak:
                    url: http://localhost:8001/documenten/api/v1
                    clientId: valtimo_client
                    secret: e09b8bc5-5831-4618-ab28-41411304309d
                    rsin: "051845623"
                    documentTypeUrl: http://host.docker.internal:8001/catalogi/api/v1/informatieobjecttypen/efc332f2-be3b-4bad-9e3c-49a6219c92ad
                dummydoc:
                    url: http://localhost:8002/documenten/api/v1
                    clientId: docdoc
                    secret: e09b8bc5-5831-4618-ab28-41411304309d
        berichten:
            bericht-object-type-url: http://host.docker.internal:8011/api/v1/objecttypes/78731088-430f-49fd-9a4c-80ddd42ded28
    openklant:
        url: http://localhost:8006
        clientId: valtimo_client
        secret: e09b8bc5-5831-4618-ab28-41411304309d
        rsin: "051845623"
    openformulieren:
        url: http://localhost:8003
        token: 3ca04f4c11159811877444fdb1e019b7eac13f78
    objectsapi:
        url: http://localhost:8010
        token: 182c13e2209161852c53cef53a879f7a2f923430
    security:
        cors:
            -   path: "/**"
                config:
                    allowedHeaders: "*"
                    allowedOrigins: "*"
                    allowedMethods: "*"
        endpoints:
            unsecured: /api/public/**
    payment:
        ogone:
            url: https://secure.ogone.com/ncol/test/orderstandard.asp
            sha-out-parameters: AAVADDRESS,AAVCHECK,AAVMAIL,AAVNAME,AAVPHONE,AAVZIP,ACCEPTANCE,ALIAS,AMOUNT,BIC,BIN,BRAND,CARDNO,CCCTY,CN,COLLECTOR_BIC,COLLECTOR_IBAN,COMPLUS,CREATION_STATUS,CREDITDEBIT,CURRENCY,CVCCHECK,DCC_COMMPERCENTAGE,DCC_CONVAMOUNT,DCC_CONVCCY,DCC_EXCHRATE,DCC_EXCHRATESOURCE,DCC_EXCHRATETS,DCC_INDICATOR,DCC_MARGINPERCENTAGE,DCC_VALIDHOURS,DIGESTCARDNO,ECI,ED,EMAIL,ENCCARDNO,FXAMOUNT,FXCURRENCY,IP,IPCTY,MANDATEID,MOBILEMODE,NBREMAILUSAGE,NBRIPUSAGE,NBRIPUSAGE_ALLTX,NBRUSAGE,NCERROR,ORDERID,PAYID,PAYIDSUB,PAYMENT_REFERENCE,PM,SCO_CATEGORY,SCORING,SEQUENCETYPE,SIGNDATE,STATUS,SUBBRAND,SUBSCRIPTION_ID,TRXDATE,VC
            configurations:
                belastingzaken:
                    pspId: TAXES
                    title: Taxes
                    shaInKey: 22222222-0000-1111-1111-222222222222
                    shaOutKey: 33333333-1111-1111-2222-555555555555
                    failureUrl: http://localhost:3000
                    successUrl: http://localhost:3000
    dmn:
        url: http://localhost:8010
    prefill:
        typeUrl: http://localhost:8010
    product:
        product-details-type-url: http://localhost:8010
        product-instantie-type-url: http://localhost:8010
        product-type-url: http://localhost:8010
        product-verbruiks-object-type-url: http://localhost:8010
