name: Build and Push Docker Image

on:
    push:
        branches:
            - "main"
    workflow_dispatch:

env:
    GITHUB_REGISTRY: ghcr.io
    DOCKER_IMAGE_NAME: portal-backend
    GITHUB_NAMESPACE: nl-portal
    JAVA_VERSION: '21'

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            tagToDeploy: ${{ steps.prep.outputs.image_tag }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK ${{ env.JAVA_VERSION }}
              uses: actions/setup-java@v4
              with:
                    java-version: '${{ env.JAVA_VERSION }}'
                    distribution: 'temurin'

            - name: 'Generate unique docker tag to deploy'
              id: prep
              run: |
                  branch=${GITHUB_REF##*/}
                  sha=${GITHUB_SHA::8}
                  ts=$(date +'%Y%m%d%H%M')
                  echo "image_tag=${branch}-${ts}-${sha}" >> "$GITHUB_OUTPUT"

            - name: Clean build
              run: ./gradlew clean

            - name: Build artifacts
              run: ./gradlew build

            - name: Archive build folder
              uses: actions/upload-artifact@v4
              with:
                  name: nl-portal-backend-build
                  path: build/

    deploy:
        runs-on: ubuntu-latest
        needs: [ build ]
        permissions:
            contents: read
            packages: write
            id-token: write
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 1

            -   name: Install Cosign
                uses: sigstore/cosign-installer@v3.5.0

            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v2.1.0

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3.10.0

            -   name: Download dist artifact
                uses: actions/download-artifact@v4
                with:
                    name: nl-portal-backend-build

            -   name: 'Login to github packages'
                uses: docker/login-action@v1
                with:
                    registry: ${{ env.GITHUB_REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   id: docker_meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}
                    tags: type=raw,value=${{ needs.build.outputs.tagToDeploy }}

            -   name: Build and push Docker image
                uses: docker/build-push-action@v6
                id: build-and-push
                with:
                    file: Dockerfile
                    context: .
                    push: true
                    tags: ${{ steps.docker_meta.outputs.tags }}
                    labels: ${{ steps.docker_meta.outputs.labels }}

            -   name: Sign the images with GitHub OIDC Token
                env:
                    DIGEST: ${{ steps.build-and-push.outputs.digest }}
                    TAGS: ${{ steps.docker_meta.outputs.tags }}
                run: |
                    images=""
                    for tag in ${TAGS}; do
                      images+="${tag}@${DIGEST} "
                    done
                    cosign sign --yes ${images}

            -   name: Verify the images
                run: |
                    branch=${GITHUB_REF##*/}
                    cosign verify ${{ env.GITHUB_REGISTRY }}/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}:${{ needs.build.outputs.tagToDeploy }} \
                       --certificate-identity https://github.com/${{ env.GITHUB_NAMESPACE }}/${{ env.DOCKER_IMAGE_NAME }}/.github/workflows/cicd.yaml@refs/heads/${branch} \
                       --certificate-oidc-issuer https://token.actions.githubusercontent.com | jq